### ISSUE TITLE
Composer package name is inconsistent with FINDOLOGIC's internal and external packages

### ISSUE THREAD

**Issue by howard** [findologic/plentymarkets-rest-export#1]
Current: `findologic-plentymarkets`

Examples for other uses:
* `findologic/web-common`
* `findologic/curl-bundle` ([Packagist](https://packagist.org/packages/findologic/curl-bundle))
* `findologic/libflexport` ([Packagist](https://packagist.org/packages/findologic/libflexport))

Suggested alternative name: `findologic/plentymarkets-rest-export` (consistent with the repo path)

This isn't maximum important and can wait for the next version bump, if not longer, in my opinion. The point at which we'll need this for sure is once we decide to set up an internal Packagist repository to manage our increasing number of packages.

**Comment by ihanli** [comment]
Hi,

the [fix](#10)  implemented and will be published with the next release.
