### ISSUE TITLE
Possible fatal failure caused by dissatisfied `array` type assertion in the interface of `Attributes::parseValues`

### ISSUE THREAD

**Issue by howard** [findologic/plentymarkets-rest-export#47]
Under unknown circumstances, consumers of the exporter (i.e. the importer) can fail fatally when parsing attributes, because a method receives something other than array, when the method's type specification requires one. Attached is a [log fragment](https://github.com/findologic/plentymarkets-rest-export/files/2850603/exception.log) from the importer showing the error.

Unfortunately, it's practically impossible to identify the shop triggering this issue. The logs don't say any more as can be seen from the attachment. Best guess was checking which PlentyMarkets shops on the affected system did *not* have a successful nightly import via the `import_result` table. This yielded the following:

```
+-------------------+----------------------------------+
| url               | shopkey                          |
+-------------------+----------------------------------+
| www.caramondo.de  | C433D21C4FB055C116E120447E410BD7 | -- Could not reproduce the issue.
| www.soundhaus.org | C8F3DC04537749B5F003E6FF618501FD | -- Not integrated since more than a year.
+-------------------+----------------------------------+
```

 Regardless of reproducibility, it's probably a decent idea to pass only values to `Attributes::parseValues` that are indeed arrays, so failure can be soft and controlled, instead of hard and fatal.

This doesn't seem to be a recurring issue at this point, so it doesn't have to be considered with elevated priority. If it comes up again, I will report any more information I can find here.

**Comment by howard** [comment]
More careful log inspection revealed that it's extremely likely that `C433D21C4FB055C116E120447E410BD7` caused the problem, because its parts of the nightly import log end abruptly at a progress correlating to where the error occurs. As I said, though, tried to reproduce and was unable to. Attached the [pertinent log lines](https://github.com/findologic/plentymarkets-rest-export/files/2850654/C433D21C4FB055C116E120447E410BD7.log) anyway.

**Comment by howard** [comment]
Also, I should have read Patrick's mail more carefully, because he had already found out what the likely culprit would be.

**Comment by ihanli** [comment]
@howard 
Plentymarkets' API is only stable 99% of the time which would explain why the issue isn't reproducible anymore. I think we also had a similar issue once where the API would return `null` instead of a valid payload (although the request succeeded with `200 OK`).

Anyhow, we have to options here:
* Log that the attribute values couldn't be fetched and continue the export.
* Fail gracefully (maybe by throwing a `CustomerException`?).

Do you have a preference?

**Comment by howard** [comment]
@ihanli The data would be incomplete without the attribute values, right? If this interferes with search quality, we should rather fail, so support gets a ticket and can trigger a re-import. This way we can be notified if this problem intensifies.

If reliability issues with the PlentyMarkets API are intermittent, perhaps a third option would be to extend `Client`'s retry capabilities to cover this case as well.

**Comment by howard** [comment]
Happened on a different server today as well, but wasn't noticed until now due to long running nightly imports. Log attached.
[F4244355F1CFB9F3A94F8CD690EBF37E.log](https://github.com/findologic/plentymarkets-rest-export/files/2852531/F4244355F1CFB9F3A94F8CD690EBF37E.log)
